on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ensure_nix:
    name: Check Nix
    runs-on: self-hosted
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        fail-mode: true

    - name: Check go env
      run: |
        nix develop --command \
          go env
  build_and_test:
    name: Build and test greetings app
    needs: ensure_nix
    runs-on: self-hosted
    steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Test App
      run: |
        nix develop --command \
          go test -cover ./...